// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYxsj7ILDfdh-dOwtja9blVKFNde0hrJI',
    appId: '1:1003056393426:web:c5ee16076f8ee0483c510b',
    messagingSenderId: '1003056393426',
    projectId: 'z-task-manager',
    authDomain: 'z-task-manager.firebaseapp.com',
    storageBucket: 'z-task-manager.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrONNAU_vnqOyfLrP8QLJjek5EQyEubd8',
    appId: '1:1003056393426:android:cf7f677c2740749e3c510b',
    messagingSenderId: '1003056393426',
    projectId: 'z-task-manager',
    storageBucket: 'z-task-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXkyCWVjkcGHdvS_ydIAo-ODnOFy8mFBQ',
    appId: '1:1003056393426:ios:28074534c0993bbc3c510b',
    messagingSenderId: '1003056393426',
    projectId: 'z-task-manager',
    storageBucket: 'z-task-manager.appspot.com',
    iosClientId: '1003056393426-burfrebs1k41gpm1gkfedn2jphivm4oe.apps.googleusercontent.com',
    iosBundleId: 'com.example.zTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXkyCWVjkcGHdvS_ydIAo-ODnOFy8mFBQ',
    appId: '1:1003056393426:ios:f4ce993fc58517ab3c510b',
    messagingSenderId: '1003056393426',
    projectId: 'z-task-manager',
    storageBucket: 'z-task-manager.appspot.com',
    iosClientId: '1003056393426-6hhvjq9sed70457kvp144pchnjnfc37c.apps.googleusercontent.com',
    iosBundleId: 'com.example.zTaskManager.RunnerTests',
  );
}
